# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_QT.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(946, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.MainGrid = QtWidgets.QGridLayout()
        self.MainGrid.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.MainGrid.setContentsMargins(0, -1, -1, -1)
        self.MainGrid.setObjectName("MainGrid")
        self.grid_Generators = QtWidgets.QGridLayout()
        self.grid_Generators.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.grid_Generators.setObjectName("grid_Generators")
        self.verticalLayout_geffe = QtWidgets.QVBoxLayout()
        self.verticalLayout_geffe.setObjectName("verticalLayout_geffe")
        self.pushButton_new_Geffe = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_new_Geffe.sizePolicy().hasHeightForWidth())
        self.pushButton_new_Geffe.setSizePolicy(sizePolicy)
        self.pushButton_new_Geffe.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_new_Geffe.setObjectName("pushButton_new_Geffe")
        self.verticalLayout_geffe.addWidget(self.pushButton_new_Geffe)
        self.pushButton_geffe_next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_geffe_next.setObjectName("pushButton_geffe_next")
        self.verticalLayout_geffe.addWidget(self.pushButton_geffe_next)
        self.pushButton_geffe_next_15times = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_geffe_next_15times.setObjectName("pushButton_geffe_next_15times")
        self.verticalLayout_geffe.addWidget(self.pushButton_geffe_next_15times)
        self.pushButton_geffe_fill = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_geffe_fill.setObjectName("pushButton_geffe_fill")
        self.verticalLayout_geffe.addWidget(self.pushButton_geffe_fill)
        self.grid_Generators.addLayout(self.verticalLayout_geffe, 0, 0, 1, 1)
        self.verticalLayout_stopandgo = QtWidgets.QVBoxLayout()
        self.verticalLayout_stopandgo.setObjectName("verticalLayout_stopandgo")
        self.pushButton_new_stopandgo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_new_stopandgo.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_new_stopandgo.setObjectName("pushButton_new_stopandgo")
        self.verticalLayout_stopandgo.addWidget(self.pushButton_new_stopandgo)
        self.pushButton_stopandgo_next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stopandgo_next.setObjectName("pushButton_stopandgo_next")
        self.verticalLayout_stopandgo.addWidget(self.pushButton_stopandgo_next)
        self.pushButton_stopandgo_next_15times = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stopandgo_next_15times.setObjectName("pushButton_stopandgo_next_15times")
        self.verticalLayout_stopandgo.addWidget(self.pushButton_stopandgo_next_15times)
        self.pushButton_stopandgo_fill = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stopandgo_fill.setObjectName("pushButton_stopandgo_fill")
        self.verticalLayout_stopandgo.addWidget(self.pushButton_stopandgo_fill)
        self.grid_Generators.addLayout(self.verticalLayout_stopandgo, 1, 0, 1, 1)
        self.verticalLayout_shrinking = QtWidgets.QVBoxLayout()
        self.verticalLayout_shrinking.setObjectName("verticalLayout_shrinking")
        self.pushButton_new_shrinking = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_new_shrinking.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_new_shrinking.setObjectName("pushButton_new_shrinking")
        self.verticalLayout_shrinking.addWidget(self.pushButton_new_shrinking)
        self.pushButton_shrinking_next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_shrinking_next.setObjectName("pushButton_shrinking_next")
        self.verticalLayout_shrinking.addWidget(self.pushButton_shrinking_next)
        self.pushButton_shrinking_next_15times = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_shrinking_next_15times.setObjectName("pushButton_shrinking_next_15times")
        self.verticalLayout_shrinking.addWidget(self.pushButton_shrinking_next_15times)
        self.pushButton_shrinking_fill = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_shrinking_fill.setObjectName("pushButton_shrinking_fill")
        self.verticalLayout_shrinking.addWidget(self.pushButton_shrinking_fill)
        self.grid_Generators.addLayout(self.verticalLayout_shrinking, 2, 0, 1, 1)
        self.textBrowser_geffe_results = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_geffe_results.setObjectName("textBrowser_geffe_results")
        self.grid_Generators.addWidget(self.textBrowser_geffe_results, 0, 3, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.pushButton_shrinking_test_monobit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_shrinking_test_monobit.setObjectName("pushButton_shrinking_test_monobit")
        self.verticalLayout_6.addWidget(self.pushButton_shrinking_test_monobit)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_6.addWidget(self.pushButton_5)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_6.addWidget(self.pushButton_3)
        self.grid_Generators.addLayout(self.verticalLayout_6, 2, 2, 1, 1)
        self.textBrowser_shrinking_results = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_shrinking_results.setObjectName("textBrowser_shrinking_results")
        self.grid_Generators.addWidget(self.textBrowser_shrinking_results, 2, 3, 1, 1)
        self.textBrowser_stopandgo_results = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_stopandgo_results.setObjectName("textBrowser_stopandgo_results")
        self.grid_Generators.addWidget(self.textBrowser_stopandgo_results, 1, 3, 1, 1)
        self.verticalLayout_out_stopandgo = QtWidgets.QVBoxLayout()
        self.verticalLayout_out_stopandgo.setObjectName("verticalLayout_out_stopandgo")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_out_stopandgo.addItem(spacerItem1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_out_stopandgo.addWidget(self.label_12)
        self.text_stopandgo_state = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_stopandgo_state.sizePolicy().hasHeightForWidth())
        self.text_stopandgo_state.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.text_stopandgo_state.setFont(font)
        self.text_stopandgo_state.setObjectName("text_stopandgo_state")
        self.verticalLayout_out_stopandgo.addWidget(self.text_stopandgo_state)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_out_stopandgo.addWidget(self.label_13)
        self.text_stopandgo_stream = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_stopandgo_stream.sizePolicy().hasHeightForWidth())
        self.text_stopandgo_stream.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(11)
        self.text_stopandgo_stream.setFont(font)
        self.text_stopandgo_stream.setObjectName("text_stopandgo_stream")
        self.verticalLayout_out_stopandgo.addWidget(self.text_stopandgo_stream)
        self.grid_Generators.addLayout(self.verticalLayout_out_stopandgo, 1, 1, 1, 1)
        self.verticalLayout_out_geffe = QtWidgets.QVBoxLayout()
        self.verticalLayout_out_geffe.setObjectName("verticalLayout_out_geffe")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_out_geffe.addItem(spacerItem2)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_out_geffe.addWidget(self.label_10)
        self.text_geffe_state = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_geffe_state.sizePolicy().hasHeightForWidth())
        self.text_geffe_state.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.text_geffe_state.setFont(font)
        self.text_geffe_state.setObjectName("text_geffe_state")
        self.verticalLayout_out_geffe.addWidget(self.text_geffe_state)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_out_geffe.addWidget(self.label_11)
        self.text_geffe_stream = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_geffe_stream.sizePolicy().hasHeightForWidth())
        self.text_geffe_stream.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(11)
        self.text_geffe_stream.setFont(font)
        self.text_geffe_stream.setObjectName("text_geffe_stream")
        self.verticalLayout_out_geffe.addWidget(self.text_geffe_stream)
        self.verticalLayout_out_geffe.setStretch(1, 1)
        self.verticalLayout_out_geffe.setStretch(2, 1)
        self.verticalLayout_out_geffe.setStretch(3, 1)
        self.verticalLayout_out_geffe.setStretch(4, 1)
        self.grid_Generators.addLayout(self.verticalLayout_out_geffe, 0, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.pushButton_stopandgo_test_monobit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stopandgo_test_monobit.setObjectName("pushButton_stopandgo_test_monobit")
        self.verticalLayout_5.addWidget(self.pushButton_stopandgo_test_monobit)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_5.addWidget(self.pushButton_2)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_5.addWidget(self.pushButton_8)
        self.grid_Generators.addLayout(self.verticalLayout_5, 1, 2, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.pushButton_gefe_test_monobit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_gefe_test_monobit.sizePolicy().hasHeightForWidth())
        self.pushButton_gefe_test_monobit.setSizePolicy(sizePolicy)
        self.pushButton_gefe_test_monobit.setObjectName("pushButton_gefe_test_monobit")
        self.verticalLayout_4.addWidget(self.pushButton_gefe_test_monobit)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_4.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.grid_Generators.addLayout(self.verticalLayout_4, 0, 2, 1, 1)
        self.verticalLayout_out_shrikning = QtWidgets.QVBoxLayout()
        self.verticalLayout_out_shrikning.setObjectName("verticalLayout_out_shrikning")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_out_shrikning.addItem(spacerItem5)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_out_shrikning.addWidget(self.label_14)
        self.text_shrinking_state = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_shrinking_state.sizePolicy().hasHeightForWidth())
        self.text_shrinking_state.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.text_shrinking_state.setFont(font)
        self.text_shrinking_state.setObjectName("text_shrinking_state")
        self.verticalLayout_out_shrikning.addWidget(self.text_shrinking_state)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_out_shrikning.addWidget(self.label_15)
        self.text_shrinking_stream = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_shrinking_stream.sizePolicy().hasHeightForWidth())
        self.text_shrinking_stream.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(11)
        self.text_shrinking_stream.setFont(font)
        self.text_shrinking_stream.setObjectName("text_shrinking_stream")
        self.verticalLayout_out_shrikning.addWidget(self.text_shrinking_stream)
        self.grid_Generators.addLayout(self.verticalLayout_out_shrikning, 2, 1, 1, 1)
        self.grid_Generators.setColumnMinimumWidth(0, 50)
        self.grid_Generators.setColumnMinimumWidth(1, 50)
        self.grid_Generators.setColumnMinimumWidth(2, 100)
        self.grid_Generators.setColumnMinimumWidth(3, 200)
        self.grid_Generators.setColumnStretch(0, 1)
        self.grid_Generators.setColumnStretch(1, 100)
        self.grid_Generators.setColumnStretch(2, 1)
        self.grid_Generators.setColumnStretch(3, 1)
        self.grid_Generators.setRowStretch(0, 1)
        self.grid_Generators.setRowStretch(1, 1)
        self.grid_Generators.setRowStretch(2, 1)
        self.MainGrid.addLayout(self.grid_Generators, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.spinBox_x1_size = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_x1_size.sizePolicy().hasHeightForWidth())
        self.spinBox_x1_size.setSizePolicy(sizePolicy)
        self.spinBox_x1_size.setFrame(True)
        self.spinBox_x1_size.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_x1_size.setMinimum(1)
        self.spinBox_x1_size.setProperty("value", 16)
        self.spinBox_x1_size.setObjectName("spinBox_x1_size")
        self.verticalLayout.addWidget(self.spinBox_x1_size)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_x1_config = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_x1_config.sizePolicy().hasHeightForWidth())
        self.lineEdit_x1_config.setSizePolicy(sizePolicy)
        self.lineEdit_x1_config.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_x1_config.setObjectName("lineEdit_x1_config")
        self.verticalLayout.addWidget(self.lineEdit_x1_config)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_x1_init_state = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_x1_init_state.sizePolicy().hasHeightForWidth())
        self.lineEdit_x1_init_state.setSizePolicy(sizePolicy)
        self.lineEdit_x1_init_state.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_x1_init_state.setObjectName("lineEdit_x1_init_state")
        self.verticalLayout.addWidget(self.lineEdit_x1_init_state)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.spinBox_x1_xor_bit = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_x1_xor_bit.setToolTip("-1 For random xor bit")
        self.spinBox_x1_xor_bit.setMinimum(-1)
        self.spinBox_x1_xor_bit.setMaximum(1)
        self.spinBox_x1_xor_bit.setProperty("value", -1)
        self.spinBox_x1_xor_bit.setObjectName("spinBox_x1_xor_bit")
        self.verticalLayout.addWidget(self.spinBox_x1_xor_bit)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.spinBox_x2_size = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_x2_size.sizePolicy().hasHeightForWidth())
        self.spinBox_x2_size.setSizePolicy(sizePolicy)
        self.spinBox_x2_size.setFrame(True)
        self.spinBox_x2_size.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_x2_size.setMinimum(1)
        self.spinBox_x2_size.setProperty("value", 16)
        self.spinBox_x2_size.setObjectName("spinBox_x2_size")
        self.verticalLayout.addWidget(self.spinBox_x2_size)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.lineEdit_x2_config = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_x2_config.sizePolicy().hasHeightForWidth())
        self.lineEdit_x2_config.setSizePolicy(sizePolicy)
        self.lineEdit_x2_config.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_x2_config.setObjectName("lineEdit_x2_config")
        self.verticalLayout.addWidget(self.lineEdit_x2_config)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.lineEdit_x2_init_state = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_x2_init_state.sizePolicy().hasHeightForWidth())
        self.lineEdit_x2_init_state.setSizePolicy(sizePolicy)
        self.lineEdit_x2_init_state.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_x2_init_state.setObjectName("lineEdit_x2_init_state")
        self.verticalLayout.addWidget(self.lineEdit_x2_init_state)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.spinBox_x2_xor_bit = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_x2_xor_bit.setToolTip("-1 For random xor bit")
        self.spinBox_x2_xor_bit.setMinimum(-1)
        self.spinBox_x2_xor_bit.setProperty("value", -1)
        self.spinBox_x2_xor_bit.setObjectName("spinBox_x2_xor_bit")
        self.verticalLayout.addWidget(self.spinBox_x2_xor_bit)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.spinBox_x3_size = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_x3_size.sizePolicy().hasHeightForWidth())
        self.spinBox_x3_size.setSizePolicy(sizePolicy)
        self.spinBox_x3_size.setFrame(True)
        self.spinBox_x3_size.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_x3_size.setMinimum(1)
        self.spinBox_x3_size.setProperty("value", 16)
        self.spinBox_x3_size.setObjectName("spinBox_x3_size")
        self.verticalLayout.addWidget(self.spinBox_x3_size)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.lineEdit_x3_config = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_x3_config.sizePolicy().hasHeightForWidth())
        self.lineEdit_x3_config.setSizePolicy(sizePolicy)
        self.lineEdit_x3_config.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_x3_config.setObjectName("lineEdit_x3_config")
        self.verticalLayout.addWidget(self.lineEdit_x3_config)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lineEdit_x3_init_state = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_x3_init_state.sizePolicy().hasHeightForWidth())
        self.lineEdit_x3_init_state.setSizePolicy(sizePolicy)
        self.lineEdit_x3_init_state.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_x3_init_state.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_x3_init_state.setObjectName("lineEdit_x3_init_state")
        self.verticalLayout.addWidget(self.lineEdit_x3_init_state)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.spinBox_x3_xor_bit = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_x3_xor_bit.setToolTip("-1 For random xor bit")
        self.spinBox_x3_xor_bit.setMinimum(-1)
        self.spinBox_x3_xor_bit.setProperty("value", -1)
        self.spinBox_x3_xor_bit.setObjectName("spinBox_x3_xor_bit")
        self.verticalLayout.addWidget(self.spinBox_x3_xor_bit)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.MainGrid.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.MainGrid.addWidget(self.frame, 0, 1, 1, 1)
        self.MainGrid.setColumnMinimumWidth(0, 20)
        self.MainGrid.setColumnMinimumWidth(1, 2)
        self.MainGrid.setColumnMinimumWidth(2, 20)
        self.MainGrid.setColumnStretch(0, 1)
        self.MainGrid.setColumnStretch(2, 100)
        self.gridLayout.addLayout(self.MainGrid, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 946, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_new_Geffe.setText(_translate("MainWindow", "New\n"
"Generator Geffe’go"))
        self.pushButton_geffe_next.setText(_translate("MainWindow", "Next"))
        self.pushButton_geffe_next_15times.setText(_translate("MainWindow", "Next x 15 times"))
        self.pushButton_geffe_fill.setText(_translate("MainWindow", "Fill to 20.000"))
        self.pushButton_new_stopandgo.setText(_translate("MainWindow", "New\n"
"Stop-and-Go"))
        self.pushButton_stopandgo_next.setText(_translate("MainWindow", "Next"))
        self.pushButton_stopandgo_next_15times.setText(_translate("MainWindow", "Next x 15 times"))
        self.pushButton_stopandgo_fill.setText(_translate("MainWindow", "Fill to 20.000"))
        self.pushButton_new_shrinking.setText(_translate("MainWindow", "New\n"
"Shrinking Generator"))
        self.pushButton_shrinking_next.setText(_translate("MainWindow", "Next"))
        self.pushButton_shrinking_next_15times.setText(_translate("MainWindow", "Next x 15 times"))
        self.pushButton_shrinking_fill.setText(_translate("MainWindow", "Fill to 20.000"))
        self.pushButton_shrinking_test_monobit.setText(_translate("MainWindow", "Test Mono Bit"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.label_12.setText(_translate("MainWindow", "State"))
        self.text_stopandgo_state.setPlaceholderText(_translate("MainWindow", "Blank Text"))
        self.label_13.setText(_translate("MainWindow", "Stream"))
        self.text_stopandgo_stream.setPlaceholderText(_translate("MainWindow", "Blank Text"))
        self.label_10.setText(_translate("MainWindow", "State"))
        self.text_geffe_state.setPlaceholderText(_translate("MainWindow", "Blank Text"))
        self.label_11.setText(_translate("MainWindow", "Stream"))
        self.text_geffe_stream.setPlaceholderText(_translate("MainWindow", "Blank Text"))
        self.pushButton_stopandgo_test_monobit.setText(_translate("MainWindow", "Test Mono Bit"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_gefe_test_monobit.setText(_translate("MainWindow", "Test Mono Bit"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.label_14.setText(_translate("MainWindow", "State"))
        self.text_shrinking_state.setPlaceholderText(_translate("MainWindow", "Blank Text"))
        self.label_15.setText(_translate("MainWindow", "Stream"))
        self.text_shrinking_stream.setPlaceholderText(_translate("MainWindow", "Blank Text"))
        self.label.setText(_translate("MainWindow", "x1 Register Size"))
        self.label_3.setText(_translate("MainWindow", "LFSR Config"))
        self.lineEdit_x1_config.setToolTip(_translate("MainWindow", "Specify active bits in LFSR. 0 is random value. Use deciaml values."))
        self.lineEdit_x1_config.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "Initial state"))
        self.lineEdit_x1_init_state.setToolTip(_translate("MainWindow", "0 is random value."))
        self.lineEdit_x1_init_state.setText(_translate("MainWindow", "0"))
        self.label_16.setText(_translate("MainWindow", "XOR bit"))
        self.label_9.setText(_translate("MainWindow", "x2 Register Size"))
        self.label_7.setText(_translate("MainWindow", "LFSR Config"))
        self.lineEdit_x2_config.setToolTip(_translate("MainWindow", "Specify active bits in LFSR. 0 is random value. Use deciaml values."))
        self.lineEdit_x2_config.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Initial state"))
        self.lineEdit_x2_init_state.setToolTip(_translate("MainWindow", "0 is random value."))
        self.lineEdit_x2_init_state.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "XOR bit"))
        self.label_4.setText(_translate("MainWindow", "x3 Registers Size"))
        self.label_6.setText(_translate("MainWindow", "LFSR Config"))
        self.lineEdit_x3_config.setToolTip(_translate("MainWindow", "Specify active bits in LFSR. 0 is random value. Use deciaml values."))
        self.lineEdit_x3_config.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Initial state"))
        self.lineEdit_x3_init_state.setToolTip(_translate("MainWindow", "0 is random value."))
        self.lineEdit_x3_init_state.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "XOR bit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
