# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_QT.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 798)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.MainGrid = QtWidgets.QGridLayout()
        self.MainGrid.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.MainGrid.setContentsMargins(0, -1, -1, -1)
        self.MainGrid.setObjectName("MainGrid")
        self.grid_Generators = QtWidgets.QGridLayout()
        self.grid_Generators.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.grid_Generators.setObjectName("grid_Generators")
        self.grid_config_stopandgo = QtWidgets.QGridLayout()
        self.grid_config_stopandgo.setObjectName("grid_config_stopandgo")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_config_stopandgo.addItem(spacerItem, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.grid_config_stopandgo.addWidget(self.lineEdit_4, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_config_stopandgo.addItem(spacerItem1, 0, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_2.sizePolicy().hasHeightForWidth())
        self.spinBox_2.setSizePolicy(sizePolicy)
        self.spinBox_2.setFrame(True)
        self.spinBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setProperty("value", 8)
        self.spinBox_2.setObjectName("spinBox_2")
        self.grid_config_stopandgo.addWidget(self.spinBox_2, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_9.setObjectName("label_9")
        self.grid_config_stopandgo.addWidget(self.label_9, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_config_stopandgo.addItem(spacerItem2, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName("label_7")
        self.grid_config_stopandgo.addWidget(self.label_7, 7, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.grid_config_stopandgo.addWidget(self.lineEdit_5, 8, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_8.setObjectName("label_8")
        self.grid_config_stopandgo.addWidget(self.label_8, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_config_stopandgo.addItem(spacerItem3, 9, 0, 1, 1)
        self.grid_Generators.addLayout(self.grid_config_stopandgo, 1, 0, 1, 1)
        self.grid_config_geffe = QtWidgets.QGridLayout()
        self.grid_config_geffe.setObjectName("grid_config_geffe")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.grid_config_geffe.addWidget(self.label_2, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.grid_config_geffe.addWidget(self.label, 2, 0, 1, 1)
        self.lineEdit_geffe_config = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_geffe_config.sizePolicy().hasHeightForWidth())
        self.lineEdit_geffe_config.setSizePolicy(sizePolicy)
        self.lineEdit_geffe_config.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_geffe_config.setObjectName("lineEdit_geffe_config")
        self.grid_config_geffe.addWidget(self.lineEdit_geffe_config, 9, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_config_geffe.addItem(spacerItem4, 10, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_config_geffe.addItem(spacerItem5, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.grid_config_geffe.addWidget(self.label_3, 8, 0, 1, 1)
        self.spinBox_geffe_size = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_geffe_size.sizePolicy().hasHeightForWidth())
        self.spinBox_geffe_size.setSizePolicy(sizePolicy)
        self.spinBox_geffe_size.setFrame(True)
        self.spinBox_geffe_size.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_geffe_size.setMinimum(1)
        self.spinBox_geffe_size.setProperty("value", 8)
        self.spinBox_geffe_size.setObjectName("spinBox_geffe_size")
        self.grid_config_geffe.addWidget(self.spinBox_geffe_size, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_config_geffe.addItem(spacerItem6, 4, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_config_geffe.addItem(spacerItem7, 0, 0, 1, 1)
        self.lineEdit_geffe_init_state = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_geffe_init_state.sizePolicy().hasHeightForWidth())
        self.lineEdit_geffe_init_state.setSizePolicy(sizePolicy)
        self.lineEdit_geffe_init_state.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_geffe_init_state.setObjectName("lineEdit_geffe_init_state")
        self.grid_config_geffe.addWidget(self.lineEdit_geffe_init_state, 6, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_config_geffe.addItem(spacerItem8, 1, 0, 1, 1)
        self.grid_config_geffe.setRowStretch(0, 1)
        self.grid_Generators.addLayout(self.grid_config_geffe, 0, 0, 1, 1)
        self.verticalLayout_geffe = QtWidgets.QVBoxLayout()
        self.verticalLayout_geffe.setObjectName("verticalLayout_geffe")
        self.pushButton_run_Geffe = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_run_Geffe.sizePolicy().hasHeightForWidth())
        self.pushButton_run_Geffe.setSizePolicy(sizePolicy)
        self.pushButton_run_Geffe.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_run_Geffe.setObjectName("pushButton_run_Geffe")
        self.verticalLayout_geffe.addWidget(self.pushButton_run_Geffe)
        self.pushButton_geffe_next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_geffe_next.setObjectName("pushButton_geffe_next")
        self.verticalLayout_geffe.addWidget(self.pushButton_geffe_next)
        self.pushButton_geffe_next15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_geffe_next15.setObjectName("pushButton_geffe_next15")
        self.verticalLayout_geffe.addWidget(self.pushButton_geffe_next15)
        self.grid_Generators.addLayout(self.verticalLayout_geffe, 0, 1, 1, 1)
        self.verticalLayout_stopandgo = QtWidgets.QVBoxLayout()
        self.verticalLayout_stopandgo.setObjectName("verticalLayout_stopandgo")
        self.pushButton_run_stopsndgo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_run_stopsndgo.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_run_stopsndgo.setObjectName("pushButton_run_stopsndgo")
        self.verticalLayout_stopandgo.addWidget(self.pushButton_run_stopsndgo)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_stopandgo.addWidget(self.pushButton_10)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_stopandgo.addWidget(self.pushButton_9)
        self.grid_Generators.addLayout(self.verticalLayout_stopandgo, 1, 1, 1, 1)
        self.verticalLayout_shrinking = QtWidgets.QVBoxLayout()
        self.verticalLayout_shrinking.setObjectName("verticalLayout_shrinking")
        self.pushButton_run_shrinking = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_run_shrinking.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_run_shrinking.setObjectName("pushButton_run_shrinking")
        self.verticalLayout_shrinking.addWidget(self.pushButton_run_shrinking)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_shrinking.addWidget(self.pushButton_12)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_shrinking.addWidget(self.pushButton_11)
        self.grid_Generators.addLayout(self.verticalLayout_shrinking, 2, 1, 1, 1)
        self.grid_config_shrinking = QtWidgets.QGridLayout()
        self.grid_config_shrinking.setObjectName("grid_config_shrinking")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.grid_config_shrinking.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setObjectName("label_5")
        self.grid_config_shrinking.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_6.setObjectName("label_6")
        self.grid_config_shrinking.addWidget(self.label_6, 7, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_config_shrinking.addItem(spacerItem9, 6, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.grid_config_shrinking.addWidget(self.lineEdit_6, 5, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_3.sizePolicy().hasHeightForWidth())
        self.spinBox_3.setSizePolicy(sizePolicy)
        self.spinBox_3.setFrame(True)
        self.spinBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setProperty("value", 8)
        self.spinBox_3.setObjectName("spinBox_3")
        self.grid_config_shrinking.addWidget(self.spinBox_3, 2, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.grid_config_shrinking.addWidget(self.lineEdit_7, 8, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_config_shrinking.addItem(spacerItem10, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_config_shrinking.addItem(spacerItem11, 3, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_config_shrinking.addItem(spacerItem12, 9, 0, 1, 1)
        self.grid_Generators.addLayout(self.grid_config_shrinking, 2, 0, 1, 1)
        self.verticalLayout_out_geffe = QtWidgets.QVBoxLayout()
        self.verticalLayout_out_geffe.setObjectName("verticalLayout_out_geffe")
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_out_geffe.addItem(spacerItem13)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_out_geffe.addWidget(self.label_10)
        self.text_geffe_state = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_geffe_state.sizePolicy().hasHeightForWidth())
        self.text_geffe_state.setSizePolicy(sizePolicy)
        self.text_geffe_state.setObjectName("text_geffe_state")
        self.verticalLayout_out_geffe.addWidget(self.text_geffe_state)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_out_geffe.addWidget(self.label_11)
        self.text_geffe_stream = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_geffe_stream.sizePolicy().hasHeightForWidth())
        self.text_geffe_stream.setSizePolicy(sizePolicy)
        self.text_geffe_stream.setObjectName("text_geffe_stream")
        self.verticalLayout_out_geffe.addWidget(self.text_geffe_stream)
        self.verticalLayout_out_geffe.setStretch(1, 1)
        self.verticalLayout_out_geffe.setStretch(2, 1)
        self.verticalLayout_out_geffe.setStretch(3, 1)
        self.verticalLayout_out_geffe.setStretch(4, 1)
        self.grid_Generators.addLayout(self.verticalLayout_out_geffe, 0, 2, 1, 1)
        self.verticalLayout_out_stopandgo = QtWidgets.QVBoxLayout()
        self.verticalLayout_out_stopandgo.setObjectName("verticalLayout_out_stopandgo")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_out_stopandgo.addItem(spacerItem14)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_out_stopandgo.addWidget(self.label_12)
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_5.sizePolicy().hasHeightForWidth())
        self.textBrowser_5.setSizePolicy(sizePolicy)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.verticalLayout_out_stopandgo.addWidget(self.textBrowser_5)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_out_stopandgo.addWidget(self.label_13)
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_6.sizePolicy().hasHeightForWidth())
        self.textBrowser_6.setSizePolicy(sizePolicy)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.verticalLayout_out_stopandgo.addWidget(self.textBrowser_6)
        self.grid_Generators.addLayout(self.verticalLayout_out_stopandgo, 1, 2, 1, 1)
        self.verticalLayout_out_shrikning = QtWidgets.QVBoxLayout()
        self.verticalLayout_out_shrikning.setObjectName("verticalLayout_out_shrikning")
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_out_shrikning.addItem(spacerItem15)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_out_shrikning.addWidget(self.label_14)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_3.sizePolicy().hasHeightForWidth())
        self.textBrowser_3.setSizePolicy(sizePolicy)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout_out_shrikning.addWidget(self.textBrowser_3)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_out_shrikning.addWidget(self.label_15)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_4.sizePolicy().hasHeightForWidth())
        self.textBrowser_4.setSizePolicy(sizePolicy)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.verticalLayout_out_shrikning.addWidget(self.textBrowser_4)
        self.grid_Generators.addLayout(self.verticalLayout_out_shrikning, 2, 2, 1, 1)
        self.grid_Generators.setColumnStretch(0, 1)
        self.grid_Generators.setColumnStretch(1, 1)
        self.grid_Generators.setColumnStretch(2, 4)
        self.grid_Generators.setRowStretch(0, 1)
        self.grid_Generators.setRowStretch(1, 1)
        self.grid_Generators.setRowStretch(2, 1)
        self.MainGrid.addLayout(self.grid_Generators, 0, 0, 1, 1)
        self.MainGrid.setColumnStretch(0, 2)
        self.gridLayout.addLayout(self.MainGrid, 0, 0, 1, 1)
        self.grid_Test = QtWidgets.QGridLayout()
        self.grid_Test.setObjectName("grid_Test")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.grid_Test.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.grid_Test.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.grid_Test.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.grid_Test.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.grid_Test.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.grid_Test.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.grid_Test.setColumnStretch(0, 1)
        self.grid_Test.setColumnStretch(1, 1)
        self.grid_Test.setRowStretch(0, 1)
        self.grid_Test.setRowStretch(1, 1)
        self.grid_Test.setRowStretch(2, 1)
        self.gridLayout.addLayout(self.grid_Test, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 778, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_4.setToolTip(_translate("MainWindow", "0 is random value."))
        self.lineEdit_4.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Registers Size"))
        self.label_7.setText(_translate("MainWindow", "LFSR Config"))
        self.lineEdit_5.setToolTip(_translate("MainWindow", "Specify active bits in LFSR. 0 is random value. Use deciaml values."))
        self.lineEdit_5.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Initial state"))
        self.label_2.setText(_translate("MainWindow", "Initial state"))
        self.label.setText(_translate("MainWindow", "Registers Size"))
        self.lineEdit_geffe_config.setToolTip(_translate("MainWindow", "Specify active bits in LFSR. 0 is random value. Use deciaml values."))
        self.lineEdit_geffe_config.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "LFSR Config"))
        self.lineEdit_geffe_init_state.setToolTip(_translate("MainWindow", "0 is random value."))
        self.lineEdit_geffe_init_state.setText(_translate("MainWindow", "0"))
        self.pushButton_run_Geffe.setText(_translate("MainWindow", "New\n"
"Generator Geffe’go"))
        self.pushButton_geffe_next.setText(_translate("MainWindow", "Next"))
        self.pushButton_geffe_next15.setText(_translate("MainWindow", "Next x 15"))
        self.pushButton_run_stopsndgo.setText(_translate("MainWindow", "New\n"
"Stop-and-Go"))
        self.pushButton_10.setText(_translate("MainWindow", "Next"))
        self.pushButton_9.setText(_translate("MainWindow", "Next x 15"))
        self.pushButton_run_shrinking.setText(_translate("MainWindow", "New\n"
"Shrinking Generator"))
        self.pushButton_12.setText(_translate("MainWindow", "Next"))
        self.pushButton_11.setText(_translate("MainWindow", "Next x 15"))
        self.label_4.setText(_translate("MainWindow", "Registers Size"))
        self.label_5.setText(_translate("MainWindow", "Initial state"))
        self.label_6.setText(_translate("MainWindow", "LFSR Config"))
        self.lineEdit_6.setToolTip(_translate("MainWindow", "0 is random value."))
        self.lineEdit_6.setText(_translate("MainWindow", "0"))
        self.lineEdit_7.setToolTip(_translate("MainWindow", "Specify active bits in LFSR. 0 is random value. Use deciaml values."))
        self.lineEdit_7.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "State"))
        self.label_11.setText(_translate("MainWindow", "Stream"))
        self.label_12.setText(_translate("MainWindow", "State"))
        self.label_13.setText(_translate("MainWindow", "Stream"))
        self.label_14.setText(_translate("MainWindow", "State"))
        self.label_15.setText(_translate("MainWindow", "Stream"))
        self.pushButton.setText(_translate("MainWindow", "Test 1"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
