# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_QT.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 585)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.MainGrid = QtWidgets.QGridLayout()
        self.MainGrid.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.MainGrid.setContentsMargins(0, -1, -1, -1)
        self.MainGrid.setObjectName("MainGrid")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_run_stopsndgo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_run_stopsndgo.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_run_stopsndgo.setObjectName("pushButton_run_stopsndgo")
        self.gridLayout_3.addWidget(self.pushButton_run_stopsndgo, 1, 0, 1, 1)
        self.pushButton_run_Geffe = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_run_Geffe.sizePolicy().hasHeightForWidth())
        self.pushButton_run_Geffe.setSizePolicy(sizePolicy)
        self.pushButton_run_Geffe.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_run_Geffe.setObjectName("pushButton_run_Geffe")
        self.gridLayout_3.addWidget(self.pushButton_run_Geffe, 0, 0, 1, 1)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setMinimumSize(QtCore.QSize(100, 20))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.gridLayout_3.addWidget(self.textBrowser_3, 0, 1, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setMinimumSize(QtCore.QSize(100, 20))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_3.addWidget(self.textBrowser_2, 2, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(100, 20))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_3.addWidget(self.textBrowser, 1, 1, 1, 1)
        self.pushButton_run_shrinking = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_run_shrinking.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_run_shrinking.setObjectName("pushButton_run_shrinking")
        self.gridLayout_3.addWidget(self.pushButton_run_shrinking, 2, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 3)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_3.setRowStretch(1, 1)
        self.gridLayout_3.setRowStretch(2, 1)
        self.MainGrid.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.MainGrid.setColumnStretch(0, 2)
        self.gridLayout.addLayout(self.MainGrid, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 22))
        self.menubar.setObjectName("menubar")
        self.actionMenuAuth = QtWidgets.QMenu(self.menubar)
        self.actionMenuAuth.setObjectName("actionMenuAuth")
        self.actionMenuRefresh_Gui = QtWidgets.QMenu(self.menubar)
        self.actionMenuRefresh_Gui.setObjectName("actionMenuRefresh_Gui")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionRefresh_GUI = QtWidgets.QAction(MainWindow)
        self.actionRefresh_GUI.setObjectName("actionRefresh_GUI")
        self.actionWho_am_I = QtWidgets.QAction(MainWindow)
        self.actionWho_am_I.setObjectName("actionWho_am_I")
        self.actionTweet_Description = QtWidgets.QAction(MainWindow)
        self.actionTweet_Description.setObjectName("actionTweet_Description")
        self.actionMenuAuth.addAction(self.actionLogin)
        self.actionMenuAuth.addAction(self.actionWho_am_I)
        self.actionMenuRefresh_Gui.addAction(self.actionRefresh_GUI)
        self.menuHelp.addAction(self.actionTweet_Description)
        self.menubar.addAction(self.actionMenuAuth.menuAction())
        self.menubar.addAction(self.actionMenuRefresh_Gui.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_run_stopsndgo.setText(_translate("MainWindow", "Stop-and-Go"))
        self.pushButton_run_Geffe.setText(_translate("MainWindow", "Generator Geffe’go"))
        self.pushButton_run_shrinking.setText(_translate("MainWindow", "Shrinking Generator"))
        self.pushButton.setText(_translate("MainWindow", "Test 1"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.actionMenuAuth.setTitle(_translate("MainWindow", "Auth"))
        self.actionMenuRefresh_Gui.setTitle(_translate("MainWindow", "GUI"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionRefresh_GUI.setText(_translate("MainWindow", "Refresh"))
        self.actionWho_am_I.setText(_translate("MainWindow", "Who am I?"))
        self.actionTweet_Description.setText(_translate("MainWindow", "Tweet Description"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
